execute: 
  echo: true

format: 
  revealjs:
    overview: true
    slide-number: "c/t"
    code-line-numbers: false
    theme: 
    - style.scss

# --- Hook, der nach dem Rendern ausgeführt wird ---
hooks:
  post-render: |
    import shutil
    shutil.make_archive("output", "zip", "_site")