project:
  type: book

book:
  title: "Bausteine Computergestützter Datenanalyse"
  subtitle: "Werkzeugbaustein R und RStudio"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Franca Hollmann
    - Marc Fehr
    - Maik Poetzsch
    - Sebastian Seipel
  date: today


  language: de-DE
  downloads: [pdf]
  repo-url: "https://github.com/bausteine-der-datenanalyse/titel"
  repo-actions: [source]
  favicon: "skript/00-bilder/favicon_bcd_new.svg"
  sidebar:
    title: "Titel"
    logo: "skript/00-bilder/logo_bcd_new.svg"

bibliography: skript/references.bib

## Formatoption / formating options
format:
  html:
    ## Logo
    ### Logo in Quarto Books
    favicon: "skript/00-bilder/favicon_bcd_new.svg"
    
    ### Logo in HTML
    include-in-header:
      text: |
        <link rel="shortcut icon" href="skript/00-bilder/favicon_bcd_new.svg" />
        <link rel="icon" type="image/x-icon" href="logo.ico">
    
    default-image-extension: svg
    code-copy: true # hover is default
  pdf:
    cite-method: biblatex
    biblio-title: Quellen
    default-image-extension: pdf # Vektorgrafiken werden als PDF eingebunden / vector grafics are embedded as PDF

## Inhaltsverzeichnis / table of contents
toc: true
number-sections: true
number-depth: 2

## Objekteinstellungen / object options
cap-location: bottom
fig-align: center
mermaid: 
  theme: neutral 
execute:
  freeze: auto

profile:
  default: full
  group: 
    - [full]

project:  
  output-dir: output/book/
book:
  chapters:
    - index.qmd
    - skript/erste-schritte.qmd
    - skript/erste-schritte-aufgabe.qmd
    - skript/ggplot2.qmd
    - skript/einzelne-merkmale.qmd
    - skript/einzelne-merkmale-aufgabe.qmd
    - skript/kenngrößen.qmd
    - skript/kenngrößen-aufgabe.qmd
    - skript/dichtekurven.qmd
    - skript/dichtekurven-aufgabe.qmd
    - skript/zwei-merkmale.qmd
    - skript/zwei-merkmale-aufgabe.qmd
    - skript/weitere-geoms.qmd
    - skript/weitere-geoms-aufgabe.qmd
    - skript/grundlagen.qmd
    - skript/grundlagen-aufgabe.qmd
    - skript/daten-einlesen.qmd
    - skript/daten-aufbereiten.qmd
    - skript/daten-aufbereiten-aufgabe.qmd
    - skript/räumliche-daten.qmd
    - skript/räumliche-daten-aufgabe.qmd
    - skript/mehrere-datensätze.qmd
    - skript/tipps-und-tricks.qmd
    - skript/rdwd-anwenden.qmd
    - skript/lineare-trends.qmd
    - skript/zeitreihen.qmd
    - skript/schreiben-mit-quarto.qmd
    - skript/präsentationen-mit-quarto.qmd


