## Untersuchung einzelner Merkmale in R

In dieser Übungsaufgabe verwenden Sie die Ergebnisse eine Mobilitätsbefragung, die Prof. Iris Mühlenbruch mit Studierenden an der Hochschule Bochum durchgeführt hat.

### Projekt herunterladen und Dataframe anzeigen

Öffnen Sie im RStudio-Projekt zu den Aufgaben (von Moodle herunterladen) das Dokument `einzelne-merkmale-aufgaben.qmd`. Führen Sie die Datei aus und zeigen Sie in einer eigenen Folie den Dataframe `d_bo_vm` an. Erzeugen Sie mit `Render` die html-Folien und überprüfen Sie das Ergebnis.

### Entfernungen zu umliegenden Städten

Die Entfernungen von der Hochschule Bochum zu umliegenden Städten sind in der nachfolgenden Tabelle zusammengefasst.

| Stadt         | Entfernung (km) |
|---------------|-----------------|
| Essen         | 17.8            |
| Wattenscheid  | 10.2            |
| Dortmund      | 15.4            |
| Herne         | 10.7            |
| Wuppertal     | 21.4            |
| Gelsenkirchen | 14.1            |
| Mühlheim      | 27.2            |

Erzeugen Sie mithilfe des Befehls `tibble` einen entsprechenden Dataframe und stellen Sie die Entfernungen in einem geeigneten Plot dar.

### Merkmale der befragten Personen

Untersuchen Sie Merkmale der befragten Personen. Beantworten Sie hierzu die folgenden Fragen jeweils mit einem geeigneten Plot:

1.  Wie viele der befragten Personen sind weiblich, wieviele männlich?
1.  Unterscheiden sich die Anteile zwischen den Befragungen 2017 und 2019?
1.  Wie teilen sich die befragten Personen auf die Fachbereiche auf? Erstellen Sie hierzu ein Ring- oder Kreisdiagramm.

### Wahl der Verkehrsmittel

Welche Verkehrsmittel werden für den Weg zur BO verwendet? Im Einzelnen:

-   Welches Verkehrsmittel wird wie häufig genutzt?
-   Welcher Fachbereich nutzt am stärksten den ÖPNV?

### Wegezeiten

Wie lange dauert der Weg zur Hochschule Bochum? Im Einzelnen:

-   Wie sind die Wegezeiten verteilt?
-   Gibt es einen Zusammenhang zwischen Verkehrsmittel und der benötigten Zeit?
-   Welche Wegezeit wird von 75% der Befragten nicht überschritten?
-   Wie unterscheidet sich dieser 75% Anteil nach den Verkehrsmitteln?
