---
title: "Aufgaben zu räumlichen Daten"
author: "TODO: Namen eintragen"
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(lubridate)

library(sf)
library(giscoR)

load("daten/mastr-data.RData")

d_wind <- d_wind |>
  mutate(
    Inbetriebnahmedatum = ymd(Inbetriebnahmedatum),
    Inbetriebnahmejahr = year(Inbetriebnahmedatum)
  ) |>
  filter(Inbetriebnahmejahr >= 1990)

d_nuclear <- d_nuclear |>
  mutate(
    DatumEndgueltigeStilllegung = ymd(DatumEndgueltigeStilllegung),
    JahrEndgueltigeStilllegung = year(DatumEndgueltigeStilllegung)
  )
```

## Titel Folie 1

```{r}
d_nuclear |>
  select(NameKraftwerk, Leistung = Nettonennleistung, Stillegung = JahrEndgueltigeStilllegung) |>
  mutate(Leistung = Leistung / 1000) |>
  arrange(Stillegung)
```

```{r}
ggplot(data = d_wind) +
  geom_bar(mapping = aes(x = Inbetriebnahmejahr))
```

```{r}
d_wind_y <- d_wind |>
  group_by(Inbetriebnahmejahr) |>
  summarise(
    Nettonennleistung = sum(Nettonennleistung),
    NettonennleistungMedian = median(Nettonennleistung)
  ) |>
  ungroup() |>
  arrange(Inbetriebnahmejahr)
d_nuclear_y <- d_nuclear |>
  group_by(JahrEndgueltigeStilllegung) |>
  summarise(Nettonennleistung = sum(Nettonennleistung))

ggplot() +
  geom_col(
    data = d_wind_y,
    mapping = aes(x = Inbetriebnahmejahr, y = Nettonennleistung / 1000),
    fill = "steelblue", color = "black"
  ) +
  geom_col(
    data = d_nuclear_y,
    mapping = aes(
      x = JahrEndgueltigeStilllegung, y = -Nettonennleistung / 1000
    ),
    width = 1, , fill = "darkred", color = "black"
  ) +
  labs(
    title = "Windkraftanlagen und Kernenergie",
    x = "Jahr",
    y = "Leistung (MW)"
  )
```

```{r}
ggplot() +
  geom_boxplot(
    data = d_wind,
    mapping = aes(x = factor(Inbetriebnahmejahr), y = Nettonennleistung)
  ) +
  scale_x_discrete(breaks = seq(from = 1990, to = 2030, by = 10))
```

```{r}
d_de <- gisco_get_nuts(country = "Germany", nuts_level = 0, resolution = 03)
d_bl <- gisco_get_nuts(country = "Germany", nuts_level = 1, resolution = 03)
d_rb <- gisco_get_nuts(country = "Germany", nuts_level = 3, resolution = 03)
```

```{r}
d_wind_sf <- d_wind |>
  st_as_sf(coords = c("Laengengrad", "Breitengrad"), crs = "+proj=longlat", na.fail = FALSE)

ggplot() +
    geom_sf(data = d_de, fill="hotpink") +
    geom_sf(data = d_wind_sf, mapping = aes(size = Nettonennleistung, color = Inbetriebnahmejahr), alpha = 0.5) +
    geom_sf(data = d_bl, fill=NA) +
    scale_size(range = c(0.1, 1)) +
    coord_sf(xlim = c(5, 15), ylim = c(47, 56))
```

```{r}
d_wind_bl <- d_wind |>
    group_by(Bundesland) |>
    summarise(n = n()) |>
    mutate(NUTS_NAME = str_to_upper(Bundesland))

# d_wind_bl
d_bl |> left_join(d_wind_bl) |>
    ggplot() +
    geom_sf(mapping = aes(fill=n)) +
    scale_fill_steps(direction=1)
```
