## Dichtekurven und Normalverteilung in R

Laden Sie das RStudio-Projekt [04-dichtekurven-und-normalverteilung-aufgaben.zip](04-dichtekurven-und-normalverteilung-aufgaben.zip) herunter und entpacken Sie die Datei. Sie verwenden den Datensatz zu einer Geschwindigkeitsmessung an der Universitätsstraße Bochum im Jahr 2017 von Prof. Iris Mühlenbruch. Die Spalte VZ kennzeichnet dabei die Verkehrszeit (siehe <https://de.wikipedia.org/wiki/Verkehrszeiten>).

### Normalverteilung

Stellen Sie die Graphen der Normalverteilung für $\mu = 0$ und $\sigma = 1/2, 1, 2, 4$ in einem Plot dar.

Zusatzaufgabe: Füllen Sie die Bereiche unter den Kurven farbig und verwenden Sie hierfür transparente Flächen.

### Histogramm und Normalverteilung

Plotten Sie das Histogramm der Geschwindigkeiten zusammen mit der zugehörigen Normalverteilung. Stellen Sie in dem Plot zusätzlich die Werte $\mu - \sigma, \mu, \mu + \sigma$ dar. Prüfen Sie mithilfe eines NQ-Plots, ob die Werte näherungsweise normalverteilt sind.


### Histogramm und Dichtekurve

Stellen Sie das Histogramm der Geschwindigkeiten gemeinsam mit einer approximierten Dichtekurve dar. Experimentieren Sie hierbei mit verschiedenen Breiten des Kerns.


### Darstellungsformen: Dichtekurven, Violinenplots und Boxplots

Vergleichen Sie die Verteilung der Geschwindigkeiten für

-   die beiden Wochentage
-   sowie die unterschiedlichen Verkehrszeiten.

Verwenden Sie hierzu jeweils

-   übereinander angeordnete Dichtekurven,
-   Violinenplots und
-   Boxplots.

Welche Darstellungsform scheint ihnen am besten geeignet?
