
#### Einlesen und Aufbereiten der Daten

```{.r}
library(readxl)
library(tidyverse)
library(kableExtra)

d_donau <- read_delim(
    "daten/6342800.day",
    locale = locale(decimal_mark = ".", grouping_mark = ","),
    trim_ws = TRUE, skip = 40
  ) |> 
  select(Datum = "YYYY-MM-DD", Abfluss = Original) |>
  mutate(
    Monat = month(Datum, label = TRUE),
    Jahr = year(Datum)
  )
```

#### Plots der Abflüsse

###### Streuplot

```{.r}
ggplot(data = d_donau, mapping = aes(x = Datum, y = Abfluss)) + 
  geom_point(alpha = 1/3) +
  geom_smooth(method = "lm", formula = "y ~ x", se = FALSE)
```

###### Boxplot

```{.r}
ggplot(data = d_donau) +
  geom_boxplot(
    mapping = aes(x = factor(Jahr), y = Abfluss), 
    outlier.alpha = 0.3, outlier.size = 0.5
  ) + 
  scale_x_discrete(breaks = seq(1900, 2010, by = 10)) +
  labs(x = NULL, y = NULL)
```

#### Linearer Trend

```{.r}
x <- as.numeric(d_donau$Datum)
y <- d_donau$Abfluss
xmid <- mean(x)
ymid <- mean(y)
beta <- sum((x - xmid) * (y - ymid)) / sum((x - xmid)^2)
alpha <- ymid - beta * xmid
R2 <- sum((alpha + beta * x - ymid)^2) / sum((y - ymid)^2)
r2 <- cor(x, y)^2
zw <- 100 * beta * 36500  / mean(y)

paste0(
        "alpha = ", signif(alpha, 4), 
        ", beta = ", signif(beta, 4), 
        ", R^2 = ", signif(R2, 4),
        ", r^2 = ", signif(r2, 4)
       )

paste0("Zuwachs in 100 Jahren: ", round(zw, 1), "%")
```

-   Bestimmtheitsmaß mit Werten auf der Ausgleichsgeraden

-   Anstatt $R^2$ können wir auch den Korrelationskoeffizienten $r$ berechnen und quadrieren

-   Zuwachs in Hundert Jahren ist die Steigung der Ausgleichsgeraden $\beta$ mal 100 Jahre mal 365 Tage pro Jahr bezogen auf den Mittelwert und in Prozent

#### Statistische Kennwerte

Kennwerte Abfluss

```{.r}
summary(d_donau$Abfluss)
paste0("Standardabweichung Abfluss: ", sd(d_donau$Abfluss))
```

#### Standardabweichung für jedes Jahr

```{.r}
d_donau_sd <- d_donau |> 
  group_by(Jahr) |>
  summarise(sd = sd(Abfluss))
kable(d_donau_sd)
```

#### Standardabweichung über die Jahre

```{.r}
ggplot(data = d_donau_sd, mapping = aes(x = Jahr, y = sd)) +
  geom_line() +
  geom_smooth(method = "lm", formula = "y ~ x", se = FALSE)
```

-   Im linearen Trend wächst die Standardabweichung

#### Jahre mit kleinster/größter Standardabweichung

###### Jahre mit kleinster Standardabweichung

```{.r}
jahre <- (d_donau_sd |> arrange(sd) |> head(3))$Jahr
d_donau_max_sd <- d_donau |> filter(Jahr %in% jahre)
ggplot(data = d_donau_max_sd, mapping = aes(x = Datum, y = Abfluss)) +
  geom_line() +
  facet_wrap(~Jahr, scales = "free_x", ncol = 1)
```

###### Jahre mit größter Standardabweichung

```{.r}
jahre <- (d_donau_sd |> arrange(desc(sd)) |> head(3))$Jahr
d_donau_max_sd <- d_donau |> filter(Jahr %in% jahre)
ggplot(data = d_donau_max_sd, mapping = aes(x = Datum, y = Abfluss)) +
  geom_line() +
  facet_wrap(~Jahr, scales = "free_x", ncol = 1)
```

#### Weitere Jahre mit besonderem Ereignis

Jahre mit größtem und kleinsten Gesamtabfluss (Summe aller Tage)

```{.r}
d_donau_jahressumme <- d_donau |> 
  group_by(Jahr) |>
  summarise(Abfluss = sum(Abfluss)) |>
  filter(Jahr > 1900) |>
  arrange(Abfluss)
jahre <- c(head(d_donau_jahressumme, 1)$Jahr, tail(d_donau_jahressumme, 1)$Jahr)
d_donau_min_max <- d_donau |> filter(Jahr %in% jahre)
ggplot(data = d_donau_min_max, mapping = aes(x = Datum, y = Abfluss)) +
  geom_line() +
  facet_wrap(~Jahr, scales = "free_x", ncol = 1)
```

#### Monats-Mittelwerte

```{.r}
dd2 <- d_donau |> 
  group_by(Monat) |>
  summarise(
    mean = mean(Abfluss),
    q25 = quantile(Abfluss, probs = 0.25),
    q75 = quantile(Abfluss, probs = 0.75)
  )

ggplot(data = dd2, mapping = aes(group = 1)) + 
  geom_ribbon(
    mapping = aes(x = Monat, ymin = q25, ymax = q75), 
    color = "blue", fill = "light blue", alpha = 1/2
  ) +
  geom_line(mapping = aes(x = Monat, y = mean), linewidth = 1) +
  labs(y = "Abfluss")
```

-   Mittlerer Abfluss steigt zum Frühjahr an, im Herbst am kleinsten

#### Verteilung

###### Verteilung als Histogramm

```{.r}
ggplot(data = d_donau) + geom_histogram(mapping = aes(x = Abfluss), binwidth = 30) +
    labs(y = "", title = "Histogramm")
```

###### Empirische Verteilungsfunktion

```{.r}
ggplot(data = d_donau) + stat_ecdf(mapping = aes(x = Abfluss)) + 
    labs(y = "", title = "Empirische Verteilung")
```

###### Normalverteilung

```{.r}
ggplot(data = d_donau) +
  geom_histogram(mapping = aes(x = Abfluss, y = after_stat(density)), binwidth = 30) +
  stat_function(fun = \(x) dnorm(x, mean = mean(d_donau$Abfluss), sd = sd(d_donau$Abfluss)), color = "red")
```

-   Normalverteilung passt nicht gut

###### QQ-Plot

```{.r}
ggplot(data = d_donau, mapping = aes(sample = Abfluss)) +
  stat_qq() + stat_qq_line()
```

-   Auch hier ist zu erkennen, dass die Verteilung linkssteil ist.
